/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import koneksi.koneksi;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author ASUS
 */
public class MenuUtama extends javax.swing.JFrame {

    private final Connection conn = new koneksi().connect();

    /**
     * Creates new form menu_utama
     */
    public MenuUtama() {
        initComponents();
        if (UserID.getRole().equals("owner")) {
            bpengunjung.setEnabled(false);
            bwisata.setEnabled(false);
            bhotel.setEnabled(false);
            btransportasi.setEnabled(false);
            bpemesanan.setEnabled(false);
        }
    }

    public void cetak() {
        try {
            String path = "./src/Report/Data_Pegawai.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
        }
    }

    public void cetakk() {
        try {
            String path = "./src/Report/Data_Pengunjung.jasper";
            Map parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen tidak ada " + ex);
        }
    }

    public void cetak1() {
        try {
            String path = "./src/Report/Data_Transportasi.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
        }
    }

    public void cetak2() {
        try {
            String path = "./src/Report/Data_Wisata.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
        }
    }

    public void cetak3() {
        try {
            String path = "./src/Report/Data_Hotel.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
        }
    }

    public void cetak4() {
        try {
            String path = "./src/Report/Data_Oleh_Oleh.jasper";
            Map parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen tidak ada " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bwisata = new javax.swing.JButton();
        bhotel = new javax.swing.JButton();
        bpengunjung = new javax.swing.JButton();
        btransportasi = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        bpemesanan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cblaporan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("STXingkai", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wisata Kepulauan Kei");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        bwisata.setBackground(new java.awt.Color(102, 153, 255));
        bwisata.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bwisata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-floating-island-beach-32.png"))); // NOI18N
        bwisata.setText("WISATA");
        bwisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bwisataActionPerformed(evt);
            }
        });

        bhotel.setBackground(new java.awt.Color(102, 153, 255));
        bhotel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bhotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Hotel-icon.png"))); // NOI18N
        bhotel.setText("HOTEL");
        bhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhotelActionPerformed(evt);
            }
        });

        bpengunjung.setBackground(new java.awt.Color(102, 153, 255));
        bpengunjung.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bpengunjung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-myspace-app-32.png"))); // NOI18N
        bpengunjung.setText("PENGUNJUNG");
        bpengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpengunjungActionPerformed(evt);
            }
        });

        btransportasi.setBackground(new java.awt.Color(102, 153, 255));
        btransportasi.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btransportasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-taxi-32.png"))); // NOI18N
        btransportasi.setText("TRANSPORTASI");
        btransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btransportasiActionPerformed(evt);
            }
        });

        blogout.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        blogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-sign-out-32.png"))); // NOI18N
        blogout.setText("Logout");
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });

        bpemesanan.setBackground(new java.awt.Color(102, 153, 255));
        bpemesanan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bpemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-check-file-32.png"))); // NOI18N
        bpemesanan.setText("TRANSAKSI PAKET WISATA");
        bpemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpemesananActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-check-file-32.png"))); // NOI18N
        jLabel2.setText("Laporan");

        cblaporan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cblaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Data Pegawai", "Laporan Data Pengunjung", "Laporan Data Transportasi", "Laporan Data Wisata", "Laporan Data Hotel", "Laporan Data Oleh-Oleh" }));
        cblaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bpengunjung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bwisata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bhotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btransportasi, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                        .addComponent(bpemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cblaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bwisata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blogout)
                    .addComponent(jLabel2)
                    .addComponent(cblaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_blogoutActionPerformed

    private void bpemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpemesananActionPerformed
        new Transaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_bpemesananActionPerformed

    private void bpengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpengunjungActionPerformed
        new Pengunjung().setVisible(true);
        dispose();
    }//GEN-LAST:event_bpengunjungActionPerformed

    private void bwisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bwisataActionPerformed
        new Wisata().setVisible(true);
        dispose();
    }//GEN-LAST:event_bwisataActionPerformed

    private void bhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhotelActionPerformed
        new Hotel().setVisible(true);
        dispose();
    }//GEN-LAST:event_bhotelActionPerformed

    private void btransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransportasiActionPerformed
        new Transportasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btransportasiActionPerformed

    private void cblaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblaporanActionPerformed
        if (cblaporan.getSelectedItem() == "Laporan Data Pegawai") {
            cetak();
        } else if (cblaporan.getSelectedItem() == "Laporan Data Pengunjung") {
            cetakk();
        } else if (cblaporan.getSelectedItem() == "Laporan Data Transportasi") {
            cetak1();
        } else if (cblaporan.getSelectedItem() == "Laporan Data Wisata") {
            cetak2();
        } else if (cblaporan.getSelectedItem() == "Laporan Data Hotel") {
            cetak3();
        }
    }//GEN-LAST:event_cblaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhotel;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bpemesanan;
    private javax.swing.JButton bpengunjung;
    private javax.swing.JButton btransportasi;
    private javax.swing.JButton bwisata;
    private javax.swing.JComboBox<String> cblaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
